### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by enterpriseindia** [mergehez/ArgPlayer#6]
as per the documentation library successfully implemented.

After on build got 

**Android resource linking failed
AAPT: error: resource android:style/android:Widget.ImageButton not found.
error: failed linking references.**

I am using material theme is there any issue with it
`<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">`

**Comment by akbarnash** [comment]
facing same problem here, hope can find how to fix this asap
![Capture](https://user-images.githubusercontent.com/45724295/84080988-5376a980-aa07-11ea-8ed0-f2a8da91f62b.PNG)

**Comment by alijahani121** [comment]
i have same problem
AAPT: error: resource android:style/android:Widget.ImageButton not found.

**Comment by Aurangzeb365** [comment]
Anyone who fixed this issue?

**Comment by mergehez** [comment]
I removed the style with ImageButton. I hope that would help.
