### ISSUE TITLE
enableNotification()

### ISSUE THREAD

**Issue by kipchumbakevin** [mergehez/ArgPlayer#8]
Hello,. Thanks alot for this library it works well. The only problem is the enableNotification method. Its not working. The audio plays but the notification isnt showing. Kindly help, thank you

**Comment by EjazAmir** [comment]
hey, did you find any solution?

**Comment by kipchumbakevin** [comment]
Hello,. I did not find any solution

**Comment by talhamsajid** [comment]
Hey Anybody found a solution?

**Comment by kipchumbakevin** [comment]
I havent checked lately

**Comment by tolgatasci** [comment]
I think I fixed the problem.

https://github.com/mergehez/ArgPlayer/commit/ce6fa98b792dba6d512fe34c0d06b41e90f52b45

**Comment by kipchumbakevin** [comment]
Awesome thanks. I'll check it out.

**Comment by mergehez** [comment]
Hi everyone, 

Sorry for the late answer. Could you please try it again with the new version? (v3.0.1)

Note: The library's minSdkVersion is 21 now.

**Comment by kipchumbakevin** [comment]
Its working now. Thank you very much.
