### ISSUE TITLE
Only play video Once second time I got error

### ISSUE THREAD

**Issue by kingnightdrifter** [mergehez/ArgPlayer#9]
Hello dear, 

I am using this player in my project and I am facing weird problem, the problem is player is playing from file path first time and second time it is not play it is giving error.

Regards,

**Comment by mergehez** [comment]
Hi @kingnightdrifter , 

Sorry for the late answer. Could you please try it again with the new version? (v3.0.1)

Note: The library's minSdkVersion is 21 now.
